const inside='https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/45/f9/82/una-panoramica-del-nostro.jpg?h=400&s=1&w=700';
const outside='https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/a9/2f/0f/vista-esterna-del-negozietto.jpg?h=300&s=1&w=600';
const details='https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/83/75/0c/le-ardesie-con-miniature.jpg?h=400&s=1&w=700';
const pages={
 '/bomboniere/':{e:'Ricordi che restano',t:'Bomboniere personalizzate',l:'Piccoli oggetti che raccontano una giornata importante e le persone che l’hanno resa speciale.',i:details,it:'La bomboniera nasce da voi.',d:'Non partiamo da una soluzione standard. Tema, colori, materiali, confezione e messaggio vengono costruiti attorno alla vostra occasione. Ogni elemento è pensato per essere bello da ricevere e autentico da conservare.',f:['Gessi e profumatori','Calamite e cornici','Vasetti e barattolini','Confezioni coordinate']},
 '/cerimonie/':{e:'Un solo filo conduttore',t:'Cerimonie & allestimenti',l:'Dall’invito alla confettata, ogni dettaglio parla la stessa lingua.',i:outside,it:'La vostra storia, nello spazio.',d:'Arteidea accompagna matrimoni, comunioni, battesimi e ricorrenze con un progetto coerente. Partecipazioni, tableau, segnaposto e decorazioni vengono immaginati insieme per dare ritmo e personalità alla giornata.',f:['Partecipazioni','Tableau e segnaposto','Confettate','Portafedi e guest book']},
 '/idee-regalo/':{e:'Mai banale',t:'Idee regalo',l:'Un pensiero scelto bene dice molto più di quanto occupa.',i:inside,it:'Regali con una persona in mente.',d:'Per compleanni, anniversari, maestre, colleghi e feste speciali trovi creazioni pronte e tante possibilità di personalizzazione. Se l’idea non è ancora chiara, Alessia ti aiuta a trovarla.',f:['Compleanni','Maestre e colleghi','Anniversari','Ricorrenze stagionali']},
 '/nascita-battesimo/':{e:'Un dolce benvenuto',t:'Nascita & battesimo',l:'Colori, nomi e piccoli simboli per celebrare un nuovo inizio.',i:details,it:'Ogni bambino ha il suo racconto.',d:'Sacchetti, portaconfetti, calamite, cornici e composizioni coordinate vengono personalizzati con delicatezza. Dal primo pensiero alla confezione finale, tutto nasce intorno al nome e all’atmosfera scelta.',f:['Bomboniere battesimo','Sacchetti portaconfetti','Fiocchi e colori coordinati','Dettagli con il nome']},
 '/bijoux/':{e:'Uno diverso dall’altro',t:'Bijoux artigianali',l:'Accessori creativi, colorati e pieni di carattere.',i:inside,it:'Il dettaglio che cambia tutto.',d:'Collane, bracciali e accessori vengono scelti o composti per chi li indosserà. Forme, colori e piccoli elementi rendono ogni bijoux personale e difficilmente replicabile.',f:['Collane','Bracciali','Accessori','Pezzi unici']},
 '/casa/':{e:'Piccole meraviglie',t:'Casa & decorazioni',l:'Dettagli che fanno sentire uno spazio davvero tuo.',i:details,it:'Una casa parla di chi la vive.',d:'Profumatori, cornici, targhe, decorazioni stagionali e piccoli oggetti portano colore e calore negli ambienti. Puoi scegliere una creazione pronta oppure costruire una personalizzazione.',f:['Profumatori','Cornici','Targhe e messaggi','Decorazioni stagionali']},
 '/personalizzazioni/':{e:'Fatto per te',t:'Creazioni su misura',l:'Non scegli soltanto: colori, materiali e dettagli prendono forma insieme a te.',i:inside,it:'Dall’idea al pezzo unico.',d:'Racconta l’occasione, la persona e l’atmosfera che immagini. Alessia traduce questi elementi in una proposta, cura gli abbinamenti e rifinisce ogni creazione a mano. Il risultato è qualcosa che prima non esisteva.',f:['Ascolto e consulenza','Scelta di colori e materiali','Proposta coordinata','Realizzazione artigianale']},
 '/collezioni/':{e:'Tutto il mondo Arteidea',t:'Le collezioni',l:'Sei modi diversi per trovare la cosa giusta, o per iniziare a immaginarla.',i:inside,it:'Esplora, scegli, personalizza.',d:'Dalle bomboniere ai bijoux, dagli allestimenti ai piccoli dettagli per la casa: ogni categoria raccoglie ispirazioni e possibilità. Entra nella pagina che ti interessa e scopri da dove cominciare.',f:['Bomboniere','Cerimonie','Idee regalo','Nascita e battesimo','Bijoux','Casa e decorazioni']}
};
const links=[['Bomboniere','/bomboniere/'],['Cerimonie','/cerimonie/'],['Idee regalo','/idee-regalo/'],['Nascita & battesimo','/nascita-battesimo/'],['Bijoux','/bijoux/'],['Casa','/casa/']];
const p=pages[location.pathname]||pages['/collezioni/'];document.title=p.t+' | Arteidea Genova';document.getElementById('eyebrow').textContent=p.e;document.getElementById('title').textContent=p.t;document.getElementById('lead').textContent=p.l;document.getElementById('hero-image').src=p.i;document.getElementById('hero-image').alt=p.t+' Arteidea';document.getElementById('intro-title').textContent=p.it;document.getElementById('description').textContent=p.d;document.getElementById('features').innerHTML=p.f.map(x=>'<div class="feature-pill">'+x+'</div>').join('');document.getElementById('related').innerHTML=links.filter(x=>x[1]!==location.pathname).slice(0,3).map(x=>'<a class="related-card" href="'+x[1]+'"><span>Scopri la categoria</span><h3>'+x[0]+'</h3><b>Esplora →</b></a>').join('');
