import Link from "next/link";
import { Gift, Heart, MapPin } from "lucide-react";
import { collections } from "./site-data";
import { Footer, Header, TripadvisorIcon } from "./site-shell";
import { ReviewsCarousel } from "./reviews-carousel";
import { InstagramFeed } from "./instagram-feed";

export default function Home(){return <main><Header/>
  <section className="hero">
    <div className="hero-copy pop-in"><p className="kicker"><span className="kicker-bug" aria-hidden="true">🐞</span> Un negozio, mille idee</p><h1>Cose belle,<br/><em>scelte con il cuore.</em></h1><p className="hero-lead">A Sampierdarena, Arteidea riunisce bomboniere, articoli per cerimonie, bijoux, decorazioni e idee regalo in un assortimento che cambia con le stagioni e le ricorrenze. Accanto ai prodotti pronti trovi creazioni realizzate da Alessia nel suo laboratorio e personalizzazioni disponibili su articoli selezionati.</p><div className="hero-actions"><Link className="button primary" href="/collezioni">Esplora le collezioni</Link><a className="button text" href="https://wa.me/393471526803?text=Ciao%20Arteidea%2C%20vorrei%20informazioni" target="_blank" rel="noreferrer">Chiedi disponibilità</a></div><a className="hero-proof" href="https://www.tripadvisor.it/Attraction_Review-g187823-d11643904-Reviews-Arteidea-Genoa_Italian_Riviera_Liguria.html" target="_blank" rel="noreferrer" aria-label="Valutazione 5 su 5 di Arteidea su Tripadvisor"><TripadvisorIcon/><strong>5,0</strong><span>★★★★★</span><small>su Tripadvisor</small></a></div>
    <div className="hero-visual pop-in delay-1"><figure className="hero-photo main-photo"><img src="/arteidea-gallery/697.jpg" alt="L’interno colorato del negozio Arteidea"/></figure><figure className="hero-photo detail-photo"><img src="/arteidea-gallery/699.jpg" alt="Bomboniere e articoli disponibili da Arteidea"/></figure><div className="hand-note">Ogni angolo<br/><strong>ha qualcosa da raccontare</strong></div><span className="color-dot dot-one"/><span className="color-dot dot-two"/><span className="hero-burst burst-one" aria-hidden="true">🐞</span><span className="hero-burst burst-two" aria-hidden="true">✿</span><span className="hero-burst burst-three" aria-hidden="true">🐞</span></div>
  </section>

  <section className="collections-section">
    <div className="section-heading pop-in"><div><p className="kicker"><Gift size={16}/> Cosa trovi da Arteidea</p><h2>Un mondo di cose<br/><em>da scoprire.</em></h2></div><p>Le collezioni cambiano durante l’anno e comprendono oggetti scelti con cura, novità stagionali, proposte artigianali e lavorazioni di laboratorio. Ogni categoria spiega cosa trovi più spesso, quali articoli possono essere coordinati e quando è possibile richiedere una personalizzazione.</p></div>
    <div className="collection-grid collection-grid-spaced">{collections.map((item,index)=><article className={`collection-card ${item.color} ${index===0?"featured":""} pop-in`} style={{animationDelay:`${Math.min(index,5)*90}ms`}} key={item.slug}><div className="card-image"><img src={item.image} alt={item.title}/><span className={`card-sparkle ${index%3===0?"card-sparkle-bug":"card-sparkle-flower"}`} aria-hidden="true">{index%3===0?"🐞":"✿"}</span></div><div className="card-content"><span>{item.eyebrow}</span><h3>{item.title}</h3><p>{item.short}</p><Link href={`/${item.slug}`}>Entra nella categoria</Link></div></article>)}</div>
  </section>

  <section className="ways-section">
    <div className="ways-heading pop-in">
      <div className="ways-heading-copy"><p className="kicker"><span className="kicker-bug" aria-hidden="true">🐞</span> Dentro il mondo Arteidea</p><h2>Pronto, artigianale<br/><em>o personalizzato.</em></h2></div>
      <div className="ways-summary"><p>Arteidea è prima di tutto un negozio ricco di articoli pronti da scegliere. A questa selezione si affiancano creazioni che Alessia realizza o rifinisce nel laboratorio e servizi di personalizzazione disponibili soltanto quando prodotto, materiali, quantità e tempi lo permettono.</p><div className="ways-chips" aria-label="Tipi di proposta"><span>Scelto con cura</span><span>Fatto da Alessia</span><span>Su richiesta</span></div></div>
      <span className="ways-spark ways-spark-one" aria-hidden="true">🐞</span><span className="ways-spark ways-spark-two" aria-hidden="true">✿</span>
    </div>
    <div className="ways-grid">
      <article className="way-card ready pop-in"><img src="/arteidea-gallery/702.jpg" alt="Ampia selezione di prodotti disponibili in negozio"/><div><span>Da scegliere subito</span><h3>Disponibile in negozio</h3><p>Regali, accessori, bomboniere, decorazioni e piccoli pensieri già pronti. L’assortimento segue stagioni e ricorrenze, perciò colori, soggetti e modelli possono cambiare frequentemente.</p><Link href="/collezioni">Guarda le collezioni</Link></div></article>
      <article className="way-card handmade pop-in delay-1"><img src="/arteidea-gallery/703.jpg" alt="Dettagli assemblati nel laboratorio di Arteidea"/><div><span>Firmato Arteidea</span><h3>Creato da Alessia</h3><p>Composizioni, bijoux e dettagli realizzati, assemblati o rifiniti direttamente nel laboratorio. Sono lavorazioni riconoscibili, spesso disponibili in piccole quantità o legate ai materiali del momento.</p><Link href="/personalizzazioni">Scopri il laboratorio</Link></div></article>
      <article className="way-card custom pop-in delay-2"><img src="/arteidea-gallery/705.jpg" alt="Targhe e oggetti personalizzabili"/><div><span>Quando è possibile</span><h3>Personalizzabile</h3><p>Nomi, messaggi, colori e confezioni possono essere adattati su una selezione di articoli. Prima di confermare, Alessia verifica fattibilità, quantità, materiali e data di consegna.</p><Link href="/personalizzazioni">Come funziona</Link></div></article>
    </div>
  </section>

  <section className="bespoke"><div className="bespoke-sticky pop-in"><p className="kicker light"><Heart size={16}/> Il laboratorio di Alessia</p><h2>Alcune idee<br/><em>nascono qui.</em></h2><p>Nel laboratorio Arteidea Alessia realizza, assembla e rifinisce una parte delle proposte presenti in negozio. Quando l’articolo lo consente può inoltre intervenire su nomi, messaggi, colori o confezioni, spiegando prima quali modifiche sono possibili e quali tempi richiedono.</p><Link className="button cream" href="/personalizzazioni">Scopri le personalizzazioni</Link></div><div className="journey"><a className="journey-card pop-in" href="https://wa.me/393471526803?text=Ciao%20Arteidea%2C%20vorrei%20sapere%20se%20un%20articolo%20è%20personalizzabile" target="_blank" rel="noreferrer"><span className="journey-icon">💌</span><div><h3>Descrivi la richiesta</h3><p>Indica occasione, articolo, quantità, colori e data desiderata. Una fotografia di riferimento può aiutare a capire il gusto, ma la fattibilità viene sempre verificata sui materiali disponibili.</p></div><b>Invia i dettagli</b></a><Link className="journey-card pop-in delay-1" href="/personalizzazioni"><span className="journey-icon">🎨</span><div><h3>Verifica le possibilità</h3><p>Non tutto è modificabile: Alessia distingue subito tra prodotto pronto, lavorazione di laboratorio e articolo personalizzabile, proponendo soltanto soluzioni realmente realizzabili.</p></div><b>Scopri il servizio</b></Link><Link className="journey-card pop-in delay-2" href="/contatti"><span className="journey-icon">✨</span><div><h3>Scegli dal vivo</h3><p>Confrontare colori, misure, materiali e confezioni in negozio permette di decidere meglio, soprattutto per bomboniere, coordinati e ordini in quantità.</p></div><b>Orari e indirizzo</b></Link></div></section>

  <section className="gallery-section"><div className="gallery-heading pop-in"><div><p className="kicker">Uno sguardo dentro</p><h2>Il negozietto è<br/><em>una scoperta continua.</em></h2></div><p className="gallery-copy">Gli scaffali cambiano insieme alle stagioni, alle feste e alle nuove lavorazioni del laboratorio. Le fotografie raccontano solo una parte di Arteidea: passa a curiosare e lasciati sorprendere. Se cerchi un modello preciso o molte quantità, puoi anche contattarci in anticipo.</p></div><div className="gallery-grid"><figure className="gallery-large pop-in"><img src="/arteidea-gallery/698.jpg" alt="Bomboniere e accessori esposti da Arteidea"/><figcaption>Bomboniere e dettagli per le feste</figcaption></figure><figure className="pop-in delay-1"><img src="/arteidea-gallery/700.jpg" alt="Decorazioni per la casa"/><figcaption>Piccoli oggetti per la casa</figcaption></figure><figure className="pop-in delay-2"><img src="/arteidea-gallery/704.jpg" alt="Idee regalo illustrate"/><figcaption>Pensieri per ogni occasione</figcaption></figure></div></section>

  <InstagramFeed/>

  <ReviewsCarousel/>

  <section className="shop-section"><div className="shop-image"><img src="/arteidea-gallery/697.jpg" alt="Il negozio Arteidea a Sampierdarena"/><span>Il negozietto</span></div><div className="shop-info pop-in"><p className="kicker"><MapPin size={16}/> Vieni a trovarci</p><h2>Nel cuore di<br/><em>Sampierdarena.</em></h2><p className="address">Via Carlo Rolando 15R–17R, 16151 Genova</p><p>In negozio puoi vedere colori e materiali reali, confrontare le collezioni e ricevere un consiglio in base all’occasione, al budget e alla quantità. Per ordini coordinati, personalizzazioni o richieste con una data precisa, contattaci prima: potremo verificare disponibilità e tempi.</p><Link className="button shop-location-button" href="/contatti"><MapPin size={18}/> Indirizzo e orari</Link><div className="contact-row"><a href="tel:+390106465261">☎ 010 646 5261</a><a href="https://wa.me/393471526803" target="_blank" rel="noreferrer">WhatsApp</a></div></div></section>
  <section className="closing-cta"><span className="cta-flower flower-one" aria-hidden="true">✿</span><span className="cta-flower flower-two" aria-hidden="true">✿</span><span className="cta-flower flower-three" aria-hidden="true">✿</span><span className="ladybug-pop" aria-hidden="true">🐞</span><p>Il bello è entrare e guardarsi intorno</p><h2>Vieni a scoprire Arteidea.<br/><em>Se cerchi qualcosa di preciso, scrivici.</em></h2><div className="closing-actions"><Link className="button primary" href="/contatti">Vieni a trovarci</Link><a className="button secondary" href="https://wa.me/393471526803?text=Ciao%20Arteidea%2C%20sto%20cercando%20un%20articolo%20preciso" target="_blank" rel="noreferrer">Chiedi informazioni</a></div></section><Footer/>
</main>}
