import Link from "next/link";
import { Gift, Heart, MapPin, Sparkles } from "lucide-react";
import { collections } from "./site-data";
import { Footer, Header } from "./site-shell";

export default function Home(){return <main><Header/>
  <section className="hero">
    <div className="hero-copy pop-in"><p className="kicker"><Sparkles size={16}/> Un negozio, mille idee</p><h1>Cose belle,<br/><em>scelte con il cuore.</em></h1><p className="hero-lead">Oggettistica, bomboniere, bijoux e idee regalo da scoprire in negozio. Accanto alla selezione pronta, trovi creazioni nate nel laboratorio di Alessia e articoli personalizzabili su richiesta.</p><div className="hero-actions"><Link className="button primary" href="/collezioni">Esplora le collezioni</Link><a className="button text" href="https://wa.me/393471526803?text=Ciao%20Arteidea%2C%20vorrei%20informazioni" target="_blank" rel="noreferrer">Chiedi su WhatsApp</a></div><div className="hero-proof"><strong>5,0</strong><span>★★★★★</span><small>recensioni entusiaste su Tripadvisor</small></div></div>
    <div className="hero-visual pop-in delay-1"><figure className="hero-photo main-photo"><img src="/arteidea-gallery/697.jpg" alt="L’interno colorato del negozio Arteidea"/></figure><figure className="hero-photo detail-photo"><img src="/arteidea-gallery/699.jpg" alt="Bomboniere e articoli disponibili da Arteidea"/></figure><div className="hand-note">Ogni angolo<br/><strong>ha qualcosa da raccontare</strong></div><span className="color-dot dot-one"/><span className="color-dot dot-two"/></div>
  </section>

  <section className="collections-section">
    <div className="section-heading pop-in"><div><p className="kicker"><Gift size={16}/> Cosa trovi da Arteidea</p><h2>Un mondo di cose<br/><em>da scoprire.</em></h2></div><p>Le collezioni cambiano durante l’anno e mescolano oggetti scelti con cura, proposte artigianali e lavorazioni di laboratorio. Entra in una categoria per capire cosa puoi trovare.</p></div>
    <div className="collection-grid collection-grid-spaced">{collections.map((item,index)=><article className={`collection-card ${item.color} ${index===0?"featured":""} pop-in`} style={{animationDelay:`${Math.min(index,5)*90}ms`}} key={item.slug}><div className="card-image"><img src={item.image} alt={item.title}/><span className="card-sparkle" aria-hidden="true">✦</span></div><div className="card-content"><span>{item.eyebrow}</span><h3>{item.title}</h3><p>{item.short}</p><Link href={`/${item.slug}`}>Entra nella categoria</Link></div></article>)}</div>
  </section>

  <section className="ways-section">
    <div className="ways-heading pop-in"><p className="kicker">Dentro il mondo Arteidea</p><h2>Pronto, artigianale<br/><em>o personalizzato.</em></h2><p>Non tutto deve essere realizzato su misura. In negozio trovi soprattutto una ricca scelta di articoli pronti, affiancati dalle creazioni di Alessia e da personalizzazioni disponibili su prodotti selezionati.</p></div>
    <div className="ways-grid">
      <article className="way-card ready pop-in"><img src="/arteidea-gallery/702.jpg" alt="Ampia selezione di prodotti disponibili in negozio"/><div><span>Da scegliere subito</span><h3>Disponibile in negozio</h3><p>Regali, accessori, decorazioni e piccoli pensieri già pronti, con novità che seguono stagioni e ricorrenze.</p><Link href="/collezioni">Guarda le collezioni</Link></div></article>
      <article className="way-card handmade pop-in delay-1"><img src="/arteidea-gallery/703.jpg" alt="Dettagli assemblati nel laboratorio di Arteidea"/><div><span>Firmato Arteidea</span><h3>Creato da Alessia</h3><p>Composizioni e pezzi realizzati o rifiniti direttamente nel laboratorio, con il gusto colorato e riconoscibile di Arteidea.</p><Link href="/personalizzazioni">Scopri il laboratorio</Link></div></article>
      <article className="way-card custom pop-in delay-2"><img src="/arteidea-gallery/705.jpg" alt="Targhe e oggetti personalizzabili"/><div><span>Quando è possibile</span><h3>Personalizzabile</h3><p>Nomi, messaggi, colori e confezioni possono essere adattati su una selezione di articoli e progetti.</p><Link href="/personalizzazioni">Come funziona</Link></div></article>
    </div>
  </section>

  <section className="bespoke"><div className="bespoke-sticky pop-in"><p className="kicker light"><Heart size={16}/> Il laboratorio di Alessia</p><h2>Alcune idee<br/><em>nascono qui.</em></h2><p>Quando il progetto lo permette, Alessia crea, compone o personalizza il tuo articolo nel laboratorio Arteidea. Ti dirà con chiarezza cosa si può adattare e quali tempi servono.</p><Link className="button cream" href="/personalizzazioni">Scopri le personalizzazioni</Link></div><div className="journey"><a className="journey-card pop-in" href="https://wa.me/393471526803?text=Ciao%20Arteidea%2C%20vorrei%20sapere%20se%20un%20articolo%20è%20personalizzabile" target="_blank" rel="noreferrer"><span className="journey-icon">💌</span><div><h3>Racconta cosa cerchi</h3><p>Indica occasione, quantità, colori e data: riceverai una risposta concreta sulla fattibilità.</p></div><b>Scrivi su WhatsApp</b></a><Link className="journey-card pop-in delay-1" href="/personalizzazioni"><span className="journey-icon">🎨</span><div><h3>Valuta le possibilità</h3><p>Alcuni articoli sono personalizzabili, altri sono disponibili così come li vedi: troviamo la soluzione giusta.</p></div><b>Scopri il servizio</b></Link><Link className="journey-card pop-in delay-2" href="/contatti"><span className="journey-icon">✨</span><div><h3>Passa in negozio</h3><p>Vedere materiali e prodotti dal vivo è spesso il modo migliore per decidere.</p></div><b>Orari e indirizzo</b></Link></div></section>

  <section className="gallery-section"><div className="gallery-heading pop-in"><p className="kicker">Uno sguardo dentro</p><h2>Il negozietto è<br/><em>una scoperta continua.</em></h2></div><div className="gallery-grid"><figure className="gallery-large pop-in"><img src="/arteidea-gallery/698.jpg" alt="Bomboniere e accessori esposti da Arteidea"/><figcaption>Bomboniere e dettagli per le feste</figcaption></figure><figure className="pop-in delay-1"><img src="/arteidea-gallery/700.jpg" alt="Decorazioni per la casa"/><figcaption>Piccoli oggetti per la casa</figcaption></figure><figure className="pop-in delay-2"><img src="/arteidea-gallery/704.jpg" alt="Idee regalo illustrate"/><figcaption>Pensieri per ogni occasione</figcaption></figure></div></section>

  <section className="shop-section"><div className="shop-image"><img src="/arteidea-gallery/697.jpg" alt="Il negozio Arteidea a Sampierdarena"/><span>Il negozietto</span></div><div className="shop-info pop-in"><p className="kicker"><MapPin size={16}/> Vieni a trovarci</p><h2>Nel cuore di<br/><em>Sampierdarena.</em></h2><p className="address">Via Carlo Rolando 15R–17R<br/>16151 Genova</p><p>Passa a vedere dal vivo disponibilità, colori e nuove collezioni. Per personalizzazioni o quantità, scrivici prima: potremo consigliarti meglio.</p><Link className="map-link" href="/contatti">Indirizzo, orari e contatti</Link><div className="contact-row"><a href="tel:+390106465261">☎ 010 646 5261</a><a href="https://wa.me/393471526803" target="_blank" rel="noreferrer">WhatsApp</a></div></div></section>
  <section className="closing-cta"><span className="twinkle">✦</span><p>Hai già qualcosa in mente?</p><h2>Vieni a scoprirlo<br/><em>oppure raccontacelo.</em></h2><a className="button primary" href="https://wa.me/393471526803?text=Ciao%20Arteidea%2C%20vorrei%20informazioni" target="_blank" rel="noreferrer">Scrivi ad Arteidea</a></section><Footer/>
</main>}
