export type Collection = { slug:string; eyebrow:string; title:string; short:string; lead:string; intro:string; description:string; image:string; color:string; features:string[] };

export const collections: Collection[] = [
  {slug:"bomboniere",eyebrow:"Ricordi che restano",title:"Bomboniere",short:"Sacchetti, scatoline, gessi, confetti e piccoli ricordi per ogni cerimonia.",lead:"Proposte pronte, composizioni di laboratorio e personalizzazioni selezionate per una giornata importante.",intro:"Tante possibilità, una scelta più semplice.",description:"In negozio trovi un ampio assortimento di bomboniere e accessori già disponibili. Per alcuni articoli Alessia può curare confezioni, abbinamenti, nomi o dettagli coordinati; altre creazioni vengono composte direttamente nel laboratorio Arteidea.",image:"/arteidea-gallery/699.jpg",color:"lime",features:["Gessi e profumatori","Calamite e cornici","Vasetti e barattolini","Confezioni coordinate"]},
  {slug:"cerimonie",eyebrow:"Un solo filo conduttore",title:"Cerimonie & allestimenti",short:"Partecipazioni, confettate, portafedi e dettagli coordinati.",lead:"Tutto ciò che serve per accompagnare matrimoni, comunioni, battesimi e ricorrenze.",intro:"Dal dettaglio pronto al progetto coordinato.",description:"Puoi scegliere tra proposte presenti in negozio oppure, quando il servizio lo consente, costruire con Alessia un insieme coordinato. Partecipazioni, tableau, segnaposto e decorazioni vengono valutati secondo disponibilità, quantità e tempi.",image:"/arteidea-gallery/698.jpg",color:"berry",features:["Partecipazioni","Tableau e segnaposto","Confettate","Portafedi e guest book"]},
  {slug:"idee-regalo",eyebrow:"Mai banale",title:"Idee regalo",short:"Pensieri originali per compleanni, maestre e ricorrenze.",lead:"Una selezione ricca e colorata per trovare un pensiero anche quando non sai ancora quale.",intro:"Regali con una persona in mente.",description:"Per compleanni, anniversari, maestre, colleghi e feste speciali trovi soprattutto articoli pronti da scegliere. Alcune proposte sono realizzate o rifinite da Alessia e, dove indicato, possono accogliere nomi o messaggi.",image:"/arteidea-gallery/704.jpg",color:"yellow",features:["Compleanni","Maestre e colleghi","Anniversari","Ricorrenze stagionali"]},
  {slug:"nascita-battesimo",eyebrow:"Un dolce benvenuto",title:"Nascita & battesimo",short:"Colori, nomi e simboli delicati per celebrare un nuovo inizio.",lead:"Articoli pronti e soluzioni coordinate per accogliere una nuova storia.",intro:"Dolci dettagli per un nuovo inizio.",description:"Sacchetti, portaconfetti, calamite, cornici e piccoli regali sono disponibili in diverse proposte. Su articoli selezionati è possibile aggiungere nomi, colori o confezioni coordinate, verificando insieme tempi e quantità.",image:"/arteidea-gallery/701.jpg",color:"mint",features:["Bomboniere battesimo","Sacchetti portaconfetti","Fiocchi coordinati","Dettagli con il nome"]},
  {slug:"bijoux",eyebrow:"Uno diverso dall’altro",title:"Bijoux artigianali",short:"Collane, bracciali e accessori creativi pieni di colore.",lead:"Accessori pronti da indossare e pezzi composti nel laboratorio Arteidea.",intro:"Il dettaglio che cambia tutto.",description:"La selezione comprende bijoux già disponibili e creazioni assemblate da Alessia con forme, colori e piccoli elementi sempre diversi. La personalizzazione dipende dal modello e dai materiali presenti.",image:"/arteidea-gallery/703.jpg",color:"blue",features:["Collane","Bracciali","Accessori","Pezzi unici"]},
  {slug:"casa",eyebrow:"Piccole meraviglie",title:"Casa & decorazioni",short:"Profumatori, cornici, targhe e dettagli pieni di calore.",lead:"Una scelta di oggetti pronti per dare carattere alla casa o fare un regalo.",intro:"Una casa parla di chi la vive.",description:"Profumatori, cornici, targhe, decorazioni stagionali e piccoli oggetti portano colore e calore negli ambienti. La maggior parte è pronta da scegliere; alcune targhe e composizioni possono essere adattate o realizzate in laboratorio.",image:"/arteidea-gallery/700.jpg",color:"coral",features:["Profumatori","Cornici","Targhe e messaggi","Decorazioni stagionali"]},
];

export const hours = [["Lunedì","15:30–19:30"],["Martedì–Giovedì","8:30–12:30 · 15:30–19:30"],["Venerdì","8:30–19:30"],["Sabato","9:00–12:30 · 15:30–19:30"],["Domenica","Chiuso"]];
