import Link from "next/link";
import { notFound } from "next/navigation";
import { collections } from "../site-data";
import { Footer, Header } from "../site-shell";

const special={
  collezioni:{eyebrow:"Tutto il mondo Arteidea",title:"Le collezioni",lead:"Categorie diverse, unite da una selezione attenta e da un servizio che aiuta a scegliere con maggiore consapevolezza.",intro:"Un assortimento da esplorare dal vivo.",description:["Arteidea riunisce bomboniere, proposte per cerimonie, idee regalo, articoli per nascita e battesimo, bijoux e decorazioni per la casa. Le collezioni alternano prodotti pronti, novità stagionali, piccole serie e lavorazioni realizzate o rifinite da Alessia nel suo laboratorio.","Il sito racconta le principali categorie, ma non sostituisce l’esperienza in negozio: modelli, colori e disponibilità cambiano durante l’anno. Passare da Arteidea permette di confrontare materiali, dimensioni e abbinamenti, ricevendo un consiglio concreto in base alla persona o all’occasione."],note:"Puoi passare liberamente a curiosare tra gli scaffali. Se invece cerchi un modello preciso, grandi quantità o una consegna entro una certa data, una telefonata può aiutarti a trovare subito la soluzione più adatta.",image:"/arteidea-gallery/702.jpg",features:collections.map(x=>x.title)},
  personalizzazioni:{eyebrow:"Quando vuoi aggiungere qualcosa di tuo",title:"Personalizzazioni",lead:"Nomi, messaggi, colori e confezioni possono essere adattati su articoli e lavorazioni selezionate, dopo una verifica concreta di fattibilità.",intro:"Cosa può essere davvero personalizzato?",description:["Non tutti i prodotti presenti in negozio sono modificabili. La possibilità di intervenire dipende dal materiale, dal modello, dai componenti disponibili, dalla quantità richiesta e dal tempo che separa dalla consegna. Alessia valuta questi elementi prima di proporti una soluzione.","La personalizzazione può riguardare un nome, una frase, un colore, il confezionamento o il coordinamento di più elementi. Accanto a questo servizio, nel laboratorio Arteidea nascono anche composizioni e creazioni direttamente realizzate da Alessia: non semplici modifiche, ma oggetti costruiti e rifiniti con un’identità precisa."],note:"Per ricevere una valutazione utile indica sempre articolo, quantità, data desiderata e tipo di modifica. Una foto di riferimento può aiutare, ma la soluzione finale dipende dai materiali disponibili.",image:"/arteidea-gallery/705.jpg",features:["Nomi e messaggi","Colori e confezioni","Composizioni coordinate","Creazioni di laboratorio"]},
};

export default async function DetailPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;
  const item=collections.find(x=>x.slug===slug)??special[slug as keyof typeof special];
  if(!item)notFound();
  const related=collections.filter(x=>x.slug!==slug).slice(0,3);
  const tone="color" in item?item.color:slug==="personalizzazioni"?"berry":"yellow";
  return <main className={`site-inner-page tone-${tone}`}><Header/>
    <section className="inner-hero"><div className="inner-hero-copy pop-in"><nav className="breadcrumbs"><Link href="/">Home</Link>{slug!=="collezioni"&&<><span>·</span><Link href="/collezioni">Collezioni</Link></>}</nav><p className="kicker"><span className="kicker-bug" aria-hidden="true">🐞</span><span className="kicker-text">{item.eyebrow}</span></p><h1 className={item.title.length>15?"title-long":undefined}>{item.title}</h1><p className="hero-lead">{item.lead}</p><div className="page-actions"><Link className="button primary" href="/contatti">Vieni a trovarci</Link>{slug!=="collezioni"&&<Link className="button secondary" href="/collezioni">Tutte le collezioni</Link>}</div></div><div className="inner-hero-media pop-in delay-1"><img src={item.image} alt={item.title}/><span className="page-flower page-flower-one" aria-hidden="true">✿</span><span className="page-flower page-flower-two" aria-hidden="true">✿</span><span className="photo-pop">{slug==="personalizzazioni"?"Lavorazioni selezionate":"Disponibilità in negozio"} 🐞</span></div></section>
    <section className="inner-intro"><div className="inner-intro-heading pop-in"><span className="panel-flower" aria-hidden="true">✿</span><p className="kicker">Prodotti, disponibilità e servizio</p><h2>{item.intro}</h2></div><div className="inner-copy pop-in delay-1">{item.description.map(paragraph=><p key={paragraph}>{paragraph}</p>)}<div className="feature-list">{item.features.map((feature,index)=><div className="feature-pill" key={feature}><span aria-hidden="true">{index%2===0?"✿":"🐞"}</span>{feature}</div>)}</div><p className="detail-note"><strong>Un consiglio utile.</strong> {item.note}</p></div></section>
    <section className="related"><div className="related-heading pop-in"><p className="kicker">Altre proposte in negozio</p><h2>Esplora altre<br/><em>categorie Arteidea.</em></h2></div><div className="related-grid">{related.map((x,index)=><Link className="related-card pop-in" href={`/${x.slug}`} key={x.slug}><span className="related-flower" aria-hidden="true">{index===1?"🐞":"✿"}</span><small>{x.eyebrow}</small><h3>{x.title}</h3><b>Scopri la categoria</b></Link>)}</div></section>
    <section className="closing-cta"><span className="cta-flower flower-one" aria-hidden="true">✿</span><span className="cta-flower flower-two" aria-hidden="true">✿</span><span className="ladybug-pop" aria-hidden="true">🐞</span><p>Vieni a curiosare o raccontaci cosa cerchi</p><h2>Passa in negozio e lasciati ispirare.<br/><em>Per richieste precise, sentiamoci.</em></h2><div className="closing-actions"><Link className="button primary" href="/contatti">Dove siamo e orari</Link><a className="button secondary" href="tel:+390106465261">Chiama il negozio</a></div></section><Footer/>
  </main>;
}
