import { ExternalLink, Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import { Footer, Header } from "../site-shell";
import { hours } from "../site-data";

export default function ContactPage(){return <main><Header/>
  <section className="inner-hero contact-hero"><div className="inner-hero-copy pop-in"><p className="kicker"><MapPin size={16}/> Il negozietto</p><h1>Passa a trovarci.</h1><p className="hero-lead">Arteidea si trova a Genova Sampierdarena, in Via Carlo Rolando 15R–17R. In negozio puoi vedere l’assortimento disponibile, confrontare materiali e colori e spiegare ad Alessia cosa stai cercando per una cerimonia, un regalo o una ricorrenza.</p><div className="page-actions"><a className="button primary" href="https://wa.me/393471526803?text=Ciao%20Arteidea%2C%20vorrei%20informazioni" target="_blank" rel="noreferrer"><MessageCircle size={18}/> Scrivi su WhatsApp</a><a className="button secondary" href="mailto:arteidea2005@libero.it?subject=Richiesta%20dal%20sito%20Arteidea"><Mail size={18}/> Scrivi una mail</a></div></div><div className="inner-hero-media pop-in delay-1"><img src="/arteidea-gallery/697.jpg" alt="Interno del negozio Arteidea a Genova Sampierdarena"/><span className="photo-pop">Arteidea a Sampierdarena 🐞</span></div></section>
  <section className="storefront-strip"><div className="storefront-photo pop-in"><img src="/arteidea/negozio-esterno-nuovo.jpg" alt="Le insegne e l’ingresso esterno del negozio Arteidea a Genova Sampierdarena"/></div><div className="storefront-copy pop-in delay-1"><p className="kicker">Riconosci l’ingresso</p><h2>La nostra vetrina,<br/><em>piena di idee.</em></h2><p>Il negozio è al piano strada, ai civici 15R–17R di Via Carlo Rolando. Cerca l’insegna Arteidea con la coccinella: dalla vetrina puoi già riconoscere lo stile colorato e vedere una parte delle proposte del momento.</p><p>Passa liberamente a curiosare. Una telefonata è utile soprattutto se devi ritirare un ordine oppure vuoi parlare di grandi quantità, personalizzazioni o una scadenza precisa.</p><a className="button primary" href="https://www.google.com/maps/search/?api=1&query=Arteidea+Via+Carlo+Rolando+15R+Genova" target="_blank" rel="noreferrer">Portami al negozio</a></div></section>
  <section className="contact-page"><div className="pop-in"><p className="kicker">Dove siamo</p><h2>Nel cuore di<br/><em>Sampierdarena.</em></h2><p className="contact-big">Via Carlo Rolando 15R–17R<br/>16151 Genova</p><p className="contact-intro">Puoi raggiungerci direttamente con le indicazioni di Google Maps oppure contattare il negozio per controllare un articolo, chiedere informazioni su un ordine o concordare quando approfondire una richiesta.</p><div className="contact-links"><a href="https://www.google.com/maps/search/?api=1&query=Arteidea+Via+Carlo+Rolando+15R+Genova" target="_blank" rel="noreferrer">Apri Google Maps <ExternalLink size={18}/></a><a href="tel:+390106465261">010 646 5261 <Phone size={18}/></a><a href="mailto:arteidea2005@libero.it">arteidea2005@libero.it <Mail size={18}/></a></div></div><div className="contact-panel pop-in delay-1"><p className="kicker">Orari di apertura</p><div className="hours">{hours.map(([day,time])=><div key={day}><span>{day}</span><strong>{time}</strong></div>)}</div><p className="hours-note">Gli orari possono variare in occasione di festività o periodi particolari. Per personalizzazioni, ordini in quantità o ritiri con una scadenza precisa, contatta Arteidea prima di passare.</p></div></section><Footer/>
</main>}
